-- Public course content only. No user accounts, deposits or broker KYC data are stored here.
create table if not exists public.xsir_courses (
 id smallint primary key check (id between 1 and 3),
 content jsonb not null check (jsonb_typeof(content) = 'object' and content ->> 'id' = id::text),
 published boolean not null default true,
 updated_at timestamptz not null default now()
);
alter table public.xsir_courses enable row level security;
revoke all on table public.xsir_courses from anon, authenticated;
grant select on table public.xsir_courses to anon, authenticated;
create policy "Published XSIR content is publicly readable"
 on public.xsir_courses for select to anon, authenticated using (published = true);
-- Content edits happen only through the Supabase dashboard or a trusted server.
insert into public.xsir_courses(id, content) values (1, '{"id": 1, "n": "اول", "en": "LEARN", "teacher": "استاد پوریا قیومی", "role": "مدرس تخصصی سبک البروکس", "image": "pouria", "art": "learn", "summary": "منتورینگ جامع البروکس؛ ۹۵ قسمت آموزش ویدیویی + پرسش‌وپاسخ روزانه.", "more": "آشنایی با این دوره", "tag": "آموزش با همراهی مدرس", "title": "منتورینگ روزانه سبک البروکس", "product": "دورهٔ منتورینگ جامع البروکس", "description": "۹۵ قسمت ویدیوی آموزشی برای یادگیری سبک البروکس، همراه با پرسش‌وپاسخ روزانه دربارهٔ هر قسمت؛ برای اینکه ابهام‌ها رو با همراهی مدرس برطرف کنی.", "benefits": ["۹۵ قسمت آموزش", "رفع اشکال روزانه", "همراهی مدرس"], "proof": "۴ سال تدریس سبک البروکس + ترجمهٔ بیش از ۴ هزار صفحه از متون دوره‌های البروکس", "condition": "ثبت‌نام با لینک 2FX در XS + احراز هویت", "hint": "بدون نیاز به واریز", "badge1": "<b>۹۵</b> قسمت ویدیویی", "badge2": "پرسش‌وپاسخ روزانه"}'::jsonb) on conflict(id) do nothing;
insert into public.xsir_courses(id, content) values (2, '{"id": 2, "n": "دوم", "en": "LIVE", "teacher": "استاد امیر ضیایی", "role": "مدرس ارشد و مدیر تیم سیگنال پروایدر 2FX", "image": "amir", "art": "live", "summary": "چارت مستری طلا + لایو ترید ستاپ اختصاصی + باشگاه VIP قهرمانان.", "more": "آشنایی با این دوره", "tag": "آموزش در میدان عمل", "title": "ستاپ اختصاصی طلا + تحلیل و سیگنال روزانه", "product": "چارت مستری طلا + باشگاه قهرمانان", "description": "آموزش ستاپ اختصاصی طلا + لایو ترید عملی همان ستاپ روی چارت طلا + عضویت در گروه VIP باشگاه قهرمانان برای دریافت سیگنال‌ها، موقعیت‌های معاملاتی و تحلیل‌های روزانهٔ تیم 2FX.", "benefits": ["ستاپ اختصاصی طلا", "اجرای زنده", "تحلیل و موقعیت معاملاتی"], "proof": "۵ سال تدریس و لایو استریم در 2FX + مدرس بیش از ۱۰ عنوان دوره و وبینار", "condition": "ثبت‌نام و احراز هویت + مجموع واریز ۵۰ دلار", "hint": "واریز به حساب معاملاتی خودت در XS", "badge1": "<b dir=\"ltr\">VIP</b> باشگاه قهرمانان", "badge2": "لایو ترید طلا"}'::jsonb) on conflict(id) do nothing;
insert into public.xsir_courses(id, content) values (3, '{"id": 3, "n": "سوم", "en": "MASTERCLASS", "teacher": "استاد آترین", "role": "هم‌بنیان‌گذار و منتور ارشد 2FX · مبدع سبک CPM", "image": "atrin", "art": "master", "summary": "مسترکلاس نکات و تجربیات؛ عصارهٔ هشت سال تدریس و منتورینگ آترین.", "more": "آشنایی با این دوره", "tag": "تجربه، فراتر از آموزش", "title": "عصاره 8 سال ترید حرفه ای !", "product": "مسترکلاس نکات و تجربیات آترین", "description": "آرشیوی از دانسته‌ها و تجربه‌های هشت سال تدریس و منتورینگ؛ از تأسیس برند A.T.O و همراهی بیش از سه هزار دانشجوی بازارهای مالی تا ابداع پرایس اکشن مفهومی یا CPM، در یک دوره.", "benefits": ["تجربهٔ هشت‌ساله", "نکات و ریزه‌کاری‌های ترید", "نگاه یک منتور"], "proof": "هم‌بنیان‌گذار 2FX + منتور ارشد مجموعه + مبدع و صاحب سبک CPM", "condition": "ثبت‌نام و احراز هویت + مجموع واریز ۱۰۰ دلار", "hint": "اگر قبلاً ۵۰ دلار واریز کردی، ۵۰ دلار دیگر تا این دوره فاصله داری.", "badge1": "<b>۸</b> سال تجربه", "badge2": "منتور ۳۰۰۰+ دانشجو"}'::jsonb) on conflict(id) do nothing;
